config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:name, :fueltype, :gearbox, :price)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.haml
= form_for @car do |f|
  - if @car.errors.any?
    #error_explanation
      %h2= "#{pluralize(@car.errors.count, "error")} prohibited this car from being saved:"
      %ul
        - @car.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :fueltype
    = f.text_field :fueltype
  .field
    = f.label :gearbox
    = f.text_field :gearbox
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/cars/edit.html.haml
%h1 Editing car

= render 'form'

= link_to 'Show', @car
\|
= link_to 'Back', cars_path

app/views/cars/index.html.haml
%h1 Listing cars

%table
  %thead
    %tr
      %th Name
      %th Fueltype
      %th Gearbox
      %th Price
      %th
      %th
      %th

  %tbody
    - @cars.each do |car|
      %tr
        %td= car.name
        %td= car.fueltype
        %td= car.gearbox
        %td= car.price
        %td= link_to 'Show', car
        %td= link_to 'Edit', edit_car_path(car)
        %td= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Car', new_car_path

app/views/cars/new.html.haml
%h1 New car

= render 'form'

= link_to 'Back', cars_path

app/views/cars/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @car.name
%p
  %b Fueltype:
  = @car.fueltype
%p
  %b Gearbox:
  = @car.gearbox
%p
  %b Price:
  = @car.price

= link_to 'Edit', edit_car_path(@car)
\|
= link_to 'Back', cars_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Momoto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>